import { Divider, Grid, Typography } from "@mui/material";
import { Box } from "@mui/system";
import { Form, Formik } from "formik";
import BasicAlert from "../alert/alert";
import DatePickerInput from "../form/datePickerInput";
import Editor from "../form/editor";
import FileInput from "../form/fileInput";
import RadioButtonGroup from "../form/radioButtonGroup";
import SelectInput from "../form/selectInput";
import TextInput from "../form/textInput";
import Panel from "../panel/panel";
import useContentForm from "./hooks/useContentForm"

const postVisbilities = [
  { value: 'visible', label: 'Visible'},
  { value: 'hidden', label: 'Hidden'},
]

const ContentForm = () => {
  const { initialValues, handleSubmit } = useContentForm();

  return (
    <div>
      <Formik
        onSubmit={handleSubmit}
        initialValues={initialValues}
        // validationSchema={registerSchema}
      >
        {({ isSubmitting }) => (
          <Form>
            <Grid component="div" container spacing={2}>
              <Grid item xs={8}>
                <Panel style={{ marginBottom: "1rem" }}>
                  <Typography variant="h4" display="block" gutterBottom>
                    General Information
                  </Typography>
                  <Box component="div" sx={{ pb: 1 }}>
                    <TextInput
                      name='title'
                      type='text'
                      label='Blog post title'
                    />
                  </Box>
                  <Divider sx={{ mb: 2 }} />
                  <Box component="div" sx={{ pb: 1 }}>
                    <Typography variant="overline" display="block" gutterBottom>
                      Intro
                    </Typography>
                    <Editor />
                    <BasicAlert message="Please note that any HTML (including any JS code) that is entered here will be echoed (without escaping). The intro will be the only thing shown on PLUS ARTICLES for not paying users. Also on mobile, an advertisement will be shown after the intro." />
                  </Box>
                  <Box component="div" sx={{ pb: 1 }}>
                    <Typography variant="overline" display="block" gutterBottom>
                      Post body
                    </Typography>
                    <Editor />
                    <BasicAlert message="Please note that any HTML (including any JS code) that is entered here will be echoed (without escaping)." />
                  </Box>
                </Panel>
                <Panel style={{ marginBottom: "1rem" }}>
                  <Typography variant="h4" display="block" gutterBottom>
                    Search Engine Preview
                  </Typography>
                  <Box component="div" sx={{ pb: 1 }}>
                    <TextInput
                      name='slug'
                      type='text'
                      label='Slug'
                    />
                  </Box>
                  <Box component="div" sx={{ pb: 1 }}>
                    <TextInput
                      name='searchEngineTitle'
                      type='text'
                      label='Search engine title'
                      helperText="If empty, the preview shows what will be autogenerated."
                    />
                  </Box>
                  <Box component="div" sx={{ pb: 1 }}>
                    <TextInput
                      name='searchEngineDescription'
                      type='text'
                      label='Search engine description'
                      multiline
                      rows={4}
                      helperText="If empty, the preview shows what will be autogenerated."
                    />
                  </Box>
                </Panel>
              </Grid>
              <Grid item xs={4}>
                <Panel style={{ marginBottom: "1rem" }}>
                  <Typography variant="h4" display="block" gutterBottom>
                    Visibility
                  </Typography>
                  <Box component="div" sx={{ pb: 1 }}>
                    <RadioButtonGroup
                      name='postVisbilities'
                      items={postVisbilities}
                      defaultValue='visible'
                    />
                  </Box>
                  <Box component="div" sx={{ pb: 1 }}>
                    <DatePickerInput
                      label="Posted At"
                    />
                  </Box>
                </Panel>
                <Panel style={{}}>
                  <Typography variant="h4" display="block" gutterBottom>
                    Media
                  </Typography>
                  <FileInput />
                </Panel>
              </Grid>
            </Grid>
          </Form>
        )}
      </Formik>
    </div>
  )
}

export default ContentForm;
